// <auto-generated />
using EXAM_API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXAM_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231004090901_exam_api")]
    partial class exam_api
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EXAM_API.Entities.Department_Tbl", b =>
                {
                    b.Property<int>("code_department")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("code_department"));

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("number_of_personals")
                        .HasColumnType("int");

                    b.HasKey("code_department");

                    b.ToTable("Departments_Tbl");
                });

            modelBuilder.Entity("EXAM_API.Entities.Employee_Tbl", b =>
                {
                    b.Property<string>("code_employee")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("code_department")
                        .HasColumnType("int");

                    b.Property<string>("name_employee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code_employee");

                    b.HasIndex("code_department");

                    b.ToTable("Employees_Tbl");
                });

            modelBuilder.Entity("EXAM_API.Entities.Employee_Tbl", b =>
                {
                    b.HasOne("EXAM_API.Entities.Department_Tbl", "department_Tbl")
                        .WithMany("employees_Tbl")
                        .HasForeignKey("code_department")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department_Tbl");
                });

            modelBuilder.Entity("EXAM_API.Entities.Department_Tbl", b =>
                {
                    b.Navigation("employees_Tbl");
                });
#pragma warning restore 612, 618
        }
    }
}
